[CmdletBinding()]
param(
    [switch]$Skip
)

. "$PSScriptRoot\_lib.ps1"

if ($Skip) {
    Write-Host 'Skipping GStreamer bundling.'
    exit 0
}

# Prevent accidental bundling: only bundle GStreamer when explicitly allowed by env var.
if (-not $env:ALLOW_BUNDLE_GSTREAMER) {
    Write-Host 'GStreamer bundling is disabled by default (external install).'
    Write-Host 'To enable bundling for local/test builds set environment variable: $env:ALLOW_BUNDLE_GSTREAMER=1'
    exit 0
}

$repoRoot = Get-RepoRoot
$packagingRoot = Join-Path $repoRoot 'openob-embedded-installer\packaging'
$found = Get-ChildItem -Path $packagingRoot -Directory | Where-Object { $_.Name -match '^gstreamer' } | Select-Object -First 1
if (-not $found) {
    Write-Host 'No gstreamer packaging found to bundle.'
    exit 0
}
$srcGst = $found.FullName

$runtimeRoot = Get-RuntimeRoot
$destGst = Join-Path $runtimeRoot 'gstreamer'

Write-Host "Copying GStreamer: $srcGst -> $destGst"
if (Test-Path $destGst) {
    Remove-Item -Recurse -Force $destGst
}
Copy-Item -Recurse -Force $srcGst $destGst

# Try to find bin and gir paths inside the bundled folder
$binCandidate = Get-ChildItem -Path $destGst -Recurse -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'bin') } | Select-Object -First 1
$girCandidate = Get-ChildItem -Path $destGst -Recurse -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'lib\girepository-1.0') } | Select-Object -First 1
$pySiteCandidate = Get-ChildItem -Path $destGst -Recurse -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'lib\site-packages') } | Select-Object -First 1

# Create or update runtime config file with relative entries so installer is relocatable
$configDir = Join-Path $runtimeRoot 'config'
Ensure-Directory $configDir
$configPath = Join-Path $configDir 'gstreamer.env'

$gstBinRel = ''
$giTypeRel = ''
$gstPySiteRel = ''
function To-RelativePath {
    param([string]$FullPath, [string]$Base)
    $fullResolved = (Resolve-Path $FullPath).Path
    $baseResolved = (Resolve-Path $Base).Path
    if ($fullResolved.StartsWith($baseResolved)) {
        $sub = $fullResolved.Substring($baseResolved.Length).TrimStart('\')
        return ('.\' + $sub)
    }
    return $fullResolved
}
if ($binCandidate) { $gstBinRel = To-RelativePath (Join-Path $binCandidate.FullName 'bin') $runtimeRoot }
if ($girCandidate) { $giTypeRel = To-RelativePath (Join-Path $girCandidate.FullName 'lib\girepository-1.0') $runtimeRoot }
if ($pySiteCandidate) { $gstPySiteRel = To-RelativePath (Join-Path $pySiteCandidate.FullName 'lib\site-packages') $runtimeRoot }

$content = @()
$content += '# Generated by build: bundled GStreamer locations (relative to runtime root)'
if ($gstBinRel) { $content += "GstBin=$gstBinRel" }
if ($giTypeRel) { $content += "GI_TYPELIB_PATH=$giTypeRel" }
if ($gstPySiteRel) { $content += "GstPySitePackages=$gstPySiteRel" }

if ($content.Count -gt 0) {
    $content | Out-File -Encoding ASCII -FilePath $configPath -Force
    Write-Host "Wrote bundled gstreamer config to $configPath"
} else {
    Write-Host 'Could not detect bin/gir/site-packages inside bundled GStreamer; leaving existing gstreamer.env unchanged.'
}

Write-Host 'GStreamer bundled.'
